impl Drop for ThreadPool but does not compile
error[E0507]: cannot move out of `worker.thread` which is behind a mutable reference
  --> src/lib.rs:79:13
   |
79 |             worker.thread.join().unwrap();
   |             ^^^^^^^^^^^^^ move occurs because `worker.thread` has type `std::thread::JoinHandle<()>`, which does not implement the `Copy` trait